# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

get_covDD2 <- function(d_vec, l) {
    .Call(`_bs3fa_get_covDD2`, d_vec, l)
}

test <- function(d_vec, l) {
    .Call(`_bs3fa_test`, d_vec, l)
}

rnormArma <- function(mu, sig_sq) {
    .Call(`_bs3fa_rnormArma`, mu, sig_sq)
}

is_inf <- function(x) {
    .Call(`_bs3fa_is_inf`, x)
}

sample_sigsq_p <- function(a_sig, b_sig, N, RSS) {
    .Call(`_bs3fa_sample_sigsq_p`, a_sig, b_sig, N, RSS)
}

sample_sigsq_x <- function(a_sig, b_sig, D_min_mu, type) {
    .Call(`_bs3fa_sample_sigsq_x`, a_sig, b_sig, D_min_mu, type)
}

sample_sigsq_y <- function(a_sig, b_sig, D_min_mu, obs_Y, homo_var) {
    .Call(`_bs3fa_sample_sigsq_y`, a_sig, b_sig, D_min_mu, obs_Y, homo_var)
}

get_X_min_mu <- function(X, Theta, eta, xi, nu) {
    .Call(`_bs3fa_get_X_min_mu`, X, Theta, eta, xi, nu)
}

get_Y_min_mu <- function(Y, Lambda, eta) {
    .Call(`_bs3fa_get_Y_min_mu`, Y, Lambda, eta)
}

get_tau <- function(delta) {
    .Call(`_bs3fa_get_tau`, delta)
}

sample_eta_all <- function(Y, X, xi, nu, Lambda, Theta, sigsq_y, sigsq_x, obs_Y) {
    .Call(`_bs3fa_sample_eta_all`, Y, X, xi, nu, Lambda, Theta, sigsq_y, sigsq_x, obs_Y)
}

sample_nu_all <- function(X, xi, eta, Theta, sigsq_x) {
    .Call(`_bs3fa_sample_nu_all`, X, xi, eta, Theta, sigsq_x)
}

sample_xi <- function(X, nu, eta, Theta, sigsq_x, phi_xi, tau_xi) {
    .Call(`_bs3fa_sample_xi`, X, nu, eta, Theta, sigsq_x, phi_xi, tau_xi)
}

sample_phi_xi <- function(gamma_xi, tau_xi, xi) {
    .Call(`_bs3fa_sample_phi_xi`, gamma_xi, tau_xi, xi)
}

sample_delta_xi <- function(a1, a2, xi, phi_xi, delta_xi) {
    .Call(`_bs3fa_sample_delta_xi`, a1, a2, xi, phi_xi, delta_xi)
}

sample_Theta <- function(X, nu, eta, xi, sigsq_x, betasq_th, gammasq_th, tau_th) {
    .Call(`_bs3fa_sample_Theta`, X, nu, eta, xi, sigsq_x, betasq_th, gammasq_th, tau_th)
}

sample_betasq_th <- function(t, Theta, gammasq_th, tau_th) {
    .Call(`_bs3fa_sample_betasq_th`, t, Theta, gammasq_th, tau_th)
}

sample_gammasq_th <- function(s_mat, Theta, betasq_th, tau_th) {
    .Call(`_bs3fa_sample_gammasq_th`, s_mat, Theta, betasq_th, tau_th)
}

sample_s_mat <- function(gammasq_th) {
    .Call(`_bs3fa_sample_s_mat`, gammasq_th)
}

sample_t <- function(betasq_th) {
    .Call(`_bs3fa_sample_t`, betasq_th)
}

get_covDD <- function(d_vec, l) {
    .Call(`_bs3fa_get_covDD`, d_vec, l)
}

sample_Lambda <- function(Y, Lambda, eta, alpha_lam, sigsq_y, covDD, obs_Y) {
    .Call(`_bs3fa_sample_Lambda`, Y, Lambda, eta, alpha_lam, sigsq_y, covDD, obs_Y)
}

sample_Lambda_err <- function(Y, Lambda, eta, alpha_lam, sigsq_y, covDD, obs_Y) {
    .Call(`_bs3fa_sample_Lambda_err`, Y, Lambda, eta, alpha_lam, sigsq_y, covDD, obs_Y)
}

sample_psi_lam <- function(g, Lambda, delta_lam, covDD, nugget) {
    .Call(`_bs3fa_sample_psi_lam`, g, Lambda, delta_lam, covDD, nugget)
}

sample_delta_ome <- function(a1, a2, delta_ome, psi_lam, Lambda, covDD, nugget, Theta, betasq_th, gammasq_th) {
    .Call(`_bs3fa_sample_delta_ome`, a1, a2, delta_ome, psi_lam, Lambda, covDD, nugget, Theta, betasq_th, gammasq_th)
}

sample_Y_miss <- function(Lambda, eta, sigsq_y, Y, obs_Y) {
    .Call(`_bs3fa_sample_Y_miss`, Lambda, eta, sigsq_y, Y, obs_Y)
}

sample_X <- function(type, X_original, sigsq_x, Theta, eta, xi, nu) {
    .Call(`_bs3fa_sample_X`, type, X_original, sigsq_x, Theta, eta, xi, nu)
}

sample_X_init <- function(type, X_original, sigsq_x) {
    .Call(`_bs3fa_sample_X_init`, type, X_original, sigsq_x)
}

get_sqexp_kernel <- function(d_vec, l, sig, nugget) {
    .Call(`_bs3fa_get_sqexp_kernel`, d_vec, l, sig, nugget)
}

sample_eta_fpca <- function(Y, Lambda, sigsq_y, obs_Y) {
    .Call(`_bs3fa_sample_eta_fpca`, Y, Lambda, sigsq_y, obs_Y)
}

sample_delta_lam <- function(a1, a2, delta_ome, psi_lam, Lambda, covDD, nugget) {
    .Call(`_bs3fa_sample_delta_lam`, a1, a2, delta_ome, psi_lam, Lambda, covDD, nugget)
}

msf <- function(lambda, pivot) {
    .Call(`_bs3fa_msf`, lambda, pivot)
}

msfOUT <- function(lambda, pivot) {
    .Call(`_bs3fa_msfOUT`, lambda, pivot)
}

aplr <- function(matr, perm) {
    .Call(`_bs3fa_aplr`, matr, perm)
}

